# Generated by Django 4.1.2 on 2022-10-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fk1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fk9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk1')),
                ('fk10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk10')),
                ('fk11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk11')),
                ('fk12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk12')),
                ('fk13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk13')),
                ('fk14', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk14')),
                ('fk15', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk15')),
                ('fk16', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk16')),
                ('fk17', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk17')),
                ('fk18', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk18')),
                ('fk19', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk19')),
                ('fk2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk2')),
                ('fk20', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk20')),
                ('fk3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk3')),
                ('fk4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk4')),
                ('fk5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk5')),
                ('fk6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk6')),
                ('fk7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk7')),
                ('fk8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk8')),
                ('fk9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fk9')),
            ],
        ),
    ]
